### ISSUE TITLE
Personal Question: To what do you attribute your success?

### ISSUE THREAD

**Issue by tomhodgins** [xem/ama#1]
Samson's strength came from his nazirite vow, Winston Churchill had his whisky and cigar. To what do you attribute your incredible programming prowess and success?

**Comment by xem** [comment]
Hehe, thanks for these kind words!

Actually, nothing in my personal life inspires me or motivates me to program like that, my only goal is to have fun doing what I do, to keep thinking out of the box... and to entertain other people, especially when it comes to recreative programming (code-golfing, CSS/JS experiments, ...).

I also hate the conventions, so I tend to enjoy working in the fields that most "real developers" hate (CSS, character encodings, data compression, regexes, emulators, 4D, etc) and I consider my work done when I manage to get these people interested in these subjects with my work.

Also, "success" never comes quickly: my work has been unnoticed for years, so the secret is to never give up and follow your passion!

(hope I answered your question :D)

cheers,

Max
:)
