### ISSUE TITLE
How and why did you get into programming?

### ISSUE THREAD

**Issue by sindresorhus** [xem/ama#11]

**Comment by xem** [comment]
I taught myself HTML during middle school, PHP and flash during high school, and I decided I liked that. So I studied computer science at university, and there I discovered algorithmic, C, C++, Java, assembler, scheme, matlab, and many more obscure things. 5 tears after, I got back to my first love: HTML and it's now my job to develop in HTML/CSS/JS (actually I learned CSS and JS after school, when I started working for real).

Cheers,
