### ISSUE TITLE
Do you participate in mentoring or coaching others?

### ISSUE THREAD

**Issue by jedireza** [xem/ama#17]

**Comment by xem** [comment]
Hi, and thanks for your question!

I'm very shy in real life, and do not naturally try to coach / teach other people.

But at work, it happened very often that I was the only guy around knowing how to do [CSS / RegExps /  Old IE debugging / etc] and people asked me to explain them all these things, which was actually pretty fun to do.

I even prepared some talks aimed at my colleagues over the last few years ( http://xem.github.io/talks/ ) and I'd like to make more of them in the future, especially one about my latest "passion": Unicode & charsets.

Cheers!
