### ISSUE TITLE
Star Trek, Star Wars or Stargate?

### ISSUE THREAD

**Issue by arthurvr** [xem/ama#2]

**Comment by xem** [comment]
Actually I'm a huge fan of Stargate (I mean, the movie, the 3 tv shows and the two direct-to-dvd movies), and I have almost no interest in Star Wars or Star trek whatsoever. I don't know why, maybe it's to old or too popular for me ^^

PS: just followed you on twitter :)

**Comment by tomhodgins** [comment]
Stargate: Atlantis is a lot of fun :3
