### ISSUE TITLE
How do you convert the Intel SDM pdf to html

### ISSUE THREAD

**Issue by jimmysitu** [xem/ama#23]
Hi, Maxime

I found that you have converted Intel SDM to html format, which is very useful. But the SDM version is 2016 which a little bit out of date for me. Could you help me how do you convert the SDM pdf to html?

Thanks

> Intel documentation converted in 
> vol 1: http://xem.github.io/minix86/manual/intel-x86-and-64-manual-vol1/o_7281d5ea06a5b67a.html
> vol 2: http://xem.github.io/minix86/manual/intel-x86-and-64-manual-vol2/o_b5573232dd8f1481.html
> vol 3: http://xem.github.io/minix86/manual/intel-x86-and-64-manual-vol3/o_fe12b1e2a880e0ce.html

**Comment by xem** [comment]
Hello!
I'm sorry I don't have a precise answer: back then I just uploaded the PDFs in an online "PDF to HTML tool" (I don't remember which one), downloaded the zip and uploaded it on github.

Hope it helps :)
