### ISSUE TITLE
Other than JavaScript, what kind of programming are you into?

### ISSUE THREAD

**Issue by arthurvr** [xem/ama#3]

**Comment by xem** [comment]
Except HTML/CSS/JS, and a little PHP/NodeJS,

I really like C and Lua, both for the same reason: making games/homebrews on video games consoles.

I developed some DS homebrews in C with the help of libnds and PAlib (circa 2010), and in Lua with the help of microluaDS (circa 2011).

I also enjoy studying many flavours of assembler like x80 and ARMv4 to understand how consoles like the GameBoy and the GBA worked.

I also admire esoteric programming languages (https://en.wikipedia.org/wiki/Esoteric_programming_language) and APL (https://en.wikipedia.org/wiki/APL_%28programming_language%29) but never practiced any of them enough to be able to program big things.

Cheers
