### ISSUE TITLE
What does you programming environment look like?

### ISSUE THREAD

**Issue by arthurvr** [xem/ama#4]
OS, font, Terminal, color scheme, editor, ...

**Comment by xem** [comment]
Windows 8.1,
PHPStorm 8 at work, Notepad++ at home. Default settings, white background.
I do graphics with Paint. (Paint.net when I need transparency).
Hackers don't say that normally but... I hate terminals. I stay away from them as much as I can, and favorize GUIs (like Github for windows) or automatized tasks (like .bat files)
