### ISSUE TITLE
Any idea for next Js13kGames contest ? (2015 edition)

### ISSUE THREAD

**Issue by Cycymomo** [xem/ama#7]

**Comment by xem** [comment]
I'm kind of in a retro phase these days, so maybe a game a la Game&Watch, or a 8-bit / NES-like game :)

Will you compete this year?

**Comment by Cycymomo** [comment]
oh nice ! Yeah I hope I will find the time. I'm thinking about a "classic game" remastered. (like Battleship, MasterMind, etc). Depending of the theme, of course
