### ISSUE TITLE
What does your phone homescreen look like?

### ISSUE THREAD

**Issue by sindresorhus** [xem/ama#9]
Screenshot please. I ask everyone this as it tells a lot about a person. [Mine for example.](https://github.com/sindresorhus/ama/issues/64)

**Comment by xem** [comment]
Nothing very fancy: I tried a Lumia 735 this year, and almost didn't customize it.
![sans titre](https://cloud.githubusercontent.com/assets/1225909/8624306/35589074-2737-11e5-8ebb-91bae4c6070f.png)
